#!/usr/bin/env bash
# Local-build install: compiles the binary, copies it to ~/.local/bin/cmux-hub,
# re-signs on macOS, and writes ~/.local/bin/cmux-hub-restart — a standalone
# helper that starts cmux-hub for the current working directory. Invoke the
# helper from a Claude Code prompt with `!cmux-hub-restart` to launch a fresh
# hub without an LLM round-trip.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
BIN_DIR="${HOME}/.local/bin"
BINARY="${BIN_DIR}/cmux-hub"
RESTART_SCRIPT="${BIN_DIR}/cmux-hub-restart"
DEFAULTS_SRC="${REPO_DIR}/cmux-hub-plugin/defaults/actions.json"

cd "$REPO_DIR"

echo "==> Building cmux-hub binary"
bun run build:compile

mkdir -p "$BIN_DIR"
echo "==> Installing $BINARY"
cp cmux-hub "$BINARY"

if [[ "$(uname)" == "Darwin" ]]; then
  echo "==> Re-signing $BINARY"
  codesign --force --sign - "$BINARY"
fi

echo "==> Writing $RESTART_SCRIPT"
cat > "$RESTART_SCRIPT" <<EOF
#!/usr/bin/env bash
# Auto-generated by ${REPO_DIR}/scripts/install-local.sh — do not edit.
# Re-run \`bun run install:local\` in the repo to regenerate.
set -euo pipefail

CMUX_HUB="\${HOME}/.local/bin/cmux-hub"
DEFAULTS="${DEFAULTS_SRC}"

if [ ! -x "\$CMUX_HUB" ]; then
  echo "cmux-hub not found at \$CMUX_HUB" >&2
  echo "Build and install with: cd ${REPO_DIR} && bun run install:local" >&2
  exit 1
fi

if [ -f ".claude/cmux-hub.json" ]; then
  ACTIONS=".claude/cmux-hub.json"
elif [ -f "\${HOME}/.claude/cmux-hub.json" ]; then
  ACTIONS="\${HOME}/.claude/cmux-hub.json"
else
  mkdir -p "\${HOME}/.claude"
  cp "\$DEFAULTS" "\${HOME}/.claude/cmux-hub.json"
  ACTIONS="\${HOME}/.claude/cmux-hub.json"
fi

LOG_DIR="\${XDG_STATE_HOME:-\$HOME/.local/state}/cmux-hub"
mkdir -p "\$LOG_DIR"
PROJECT_NAME="\$(basename "\$PWD")"
TIMESTAMP="\$(date -u '+%Y%m%dT%H%M%SZ')"
LOG_FILE="\${LOG_DIR}/\${PROJECT_NAME}-\${TIMESTAMP}.log"

echo "[\${TIMESTAMP}] Starting cmux-hub (pwd: \$PWD)" >> "\$LOG_FILE"
"\$CMUX_HUB" --actions "\$ACTIONS" >> "\$LOG_FILE" 2>&1 &
disown
echo "cmux-hub started (pid \$!, log: \$LOG_FILE)"
EOF
chmod +x "$RESTART_SCRIPT"

cat <<EOF

Done.
  Binary:         $BINARY
  Restart helper: $RESTART_SCRIPT

Type \`!cmux-hub-restart\` in a Claude Code prompt to launch a fresh hub
without spending tokens on an LLM round-trip.
EOF
